module.exports = {
  // HTTP status messages
  ERRORS: {
    INTERNAL_SERVER_ERROR: 'Internal server error.',
    UNAUTHORIZED_NO_TOKEN: 'Unauthorized: No token provided.',
    UNAUTHORIZED_INVALID_TOKEN: 'Unauthorized: Invalid token.',
    USERNAME_PASSWORD_REQUIRED: 'Username and password are required.',
    USERNAME_TAKEN: 'Username already taken.',
    INVALID_CREDENTIALS: 'Invalid username or password.',
    CONTENT_REQUIRED: 'Content is required.',
    TITLE_REQUIRED: 'Title is required.',
    TITLE_REQUIRED_TO_SAVE: 'Title is required to save sheet.',
    TITLE_REQUIRED_TO_ARCHIVE: 'Title is required to archive sheet.',
    NO_ACTIVE_LIVE_SHEET_TO_SAVE: 'No active live sheet to save.',
    NO_ACTIVE_LIVE_SHEET_TO_ARCHIVE: 'No active live sheet to archive.',
    SAVED_SHEET_NOT_FOUND: 'Saved sheet not found.',
    CONFLICT_DETECTED: 'Conflict detected. This sheet has been updated on another device.',
    SHEET_NOT_FOUND: 'Sheet not found.',
    CATEGORY_NAME_REQUIRED: 'Category name is required.',
    CATEGORY_ALREADY_EXISTS: 'Category already exists.',
    CATEGORY_NOT_FOUND: 'Category not found.',
    WORKSPACE_NAME_REQUIRED: 'Workspace name is required.',
    WORKSPACE_NAME_TAKEN: 'Workspace name already exists.',
    WORKSPACE_NOT_FOUND: 'Workspace not found.',
    TARGET_USER_NOT_FOUND: 'Target user not found.',
    USER_NOT_FOUND: 'User not found.',
    INVALID_ACCESS_LEVEL: "Access level must be either 'member' or 'maintainer'.",
    USER_ALREADY_MEMBER: 'User is already a member of this workspace.',
    ROLES_PAYLOAD_MUST_BE_ARRAY: 'Roles payload must be an array.',
    INVALID_ROLE_ITEM: "Each role must have a valid workspaceId and access ('member' or 'maintainer').",
    UNAUTHORIZED_MAINTAINER_ONLY: 'Unauthorized: Only maintainers can add members to this workspace.',
    UNAUTHORIZED_NO_WORKSPACE_ACCESS: 'Unauthorized: You do not have access to this workspace.',
    FORBIDDEN_ADMIN_REQUIRED: 'Forbidden: Admin access required.',
    UNAUTHORIZED_NOT_WORKSPACE_MEMBER: 'Unauthorized: You do not belong to this workspace.',
    INVALID_TABLE_NAME: 'Invalid table name.',
    FILE_NOT_FOUND: 'File not found.',
    FILE_REQUIRED: 'File is required.'
  },
  MESSAGES: {
    USER_REGISTERED_SUCCESS: 'User registered successfully.',
    LOGIN_SUCCESS: 'Login successful.',
    LOGOUT_SUCCESS: 'Logged out successfully.',
    SHEET_SAVED_SUCCESS: 'Sheet saved successfully. New live sheet created.',
    SHEET_ARCHIVED_SUCCESS: 'Sheet archived successfully. New live sheet created.',
    LIVE_SHEET_DELETED: 'Live sheet deleted. Started a new blank sheet.',
    SHEET_DELETED_SUCCESS: 'Sheet deleted successfully.',
    SHEET_LOADED_SUCCESS: 'Sheet loaded into live space.',
    CATEGORY_DELETED_SUCCESS: 'Category deleted successfully.',
    AUTO_ARCHIVE_MESSAGE: 'The previous live sheet expired and was auto-archived.',
    AUTO_DELETE_MESSAGE: 'The previous live sheet expired and was deleted.',
    WORKSPACE_CREATED_SUCCESS: 'Workspace created and maintainer assigned successfully.',
    USER_ADDED_TO_WORKSPACE_SUCCESS: 'User added to workspace successfully.',
    USER_ROLES_UPDATED_SUCCESS: 'User roles updated successfully.',
    MEMBER_ADDED_SUCCESS: 'Member added successfully.',
    LIVE_SHEET_DELETED_SUCCESS: 'Live sheet deleted successfully.',
    SHEET_SAVED_SUCCESS_SHORT: 'Sheet saved successfully.',
    SHEET_ARCHIVED_SUCCESS_SHORT: 'Sheet archived successfully.',
    SESSION_REFRESH_SUCCESS: 'Session token refreshed.',
    FILE_DELETED_SUCCESS: 'File deleted successfully.',
    FILE_UPLOADED_SUCCESS: 'File uploaded successfully.'
  }
};
